### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by mararual** [MartyIce/generator-meancrud#1]
Hi,

I'm trying to use the generator after setting up a meanstack with generator-meanstack, which works correctly. However, this generator is not doing anything. Not sure if it is an incompatibility with new versions of yeoman, node, npm, or the meanstack itself.

Do you have any information on something similar?

**Comment by bobquest33** [comment]
I tried installing generator-meancrud on the git clone of mean.io and it breaks at 
yo meancrud:entity 'note'
You called the entity subgenerator with the argument note.

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/dash/Projects/mean/config/routes.js'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at EntityGenerator.readFileAsString (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/lib/actions/wiring.js:268:13)
    at EntityGenerator.files (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/entity/index.js:73:20)
    at /opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/lib/base.js:316:43
    at /opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:150:9)
    at _asyncMap (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:226:9)

**Comment by bobquest33** [comment]
I tried installing generator-meancrud on the git clone of mean.io and it breaks at 
yo meancrud:entity 'note'
You called the entity subgenerator with the argument note.

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/dash/Projects/mean/config/routes.js'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at EntityGenerator.readFileAsString (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/lib/actions/wiring.js:268:13)
    at EntityGenerator.files (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/entity/index.js:73:20)
    at /opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/lib/base.js:316:43
    at /opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:150:9)
    at _asyncMap (/opt/nodejs-0.10.24-0/nodejs/lib/node_modules/generator-meancrud/node_modules/yeoman-generator/node_modules/async/lib/async.js:226:9)

**Comment by MartyIce** [comment]
Sorry for the long delay in responding, finally got some time to work on this.  It looks like the default mean.io file/directory layout was changed, and the authors altered how certain things like routing, etc was being configured.  I've updated the generator-meancrud npm package to accomodate the latest file/directory layout.  Version 0.3 should now work against the latest mean.io stack.
